services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      FLASK_APP: app/routes.py
    depends_on:
      - test

  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    entrypoint: ["pytest", "--maxfail=1", "--disable-warnings", "--tb=short"]
    volumes:
      - .:/app
