name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Step 3: Build and test
    - name: Build and run tests
      run: |
        docker build --target test -t wordle-game:test .
        docker run --rm wordle-game:test pytest

    # Step 4: Build the production image
    - name: Build production image
      run: |
        docker build --target production -t wordle-game:latest .
